// This is an autogenerated file from Firebase Studio.
'use server';

/**
 * @fileOverview Flow for generating SEO metadata (title, description, keywords) for AI-generated exams.
 *
 * The flow takes exam content as input and returns SEO-optimized metadata.
 * @interface GenerateSeoMetadataInput - Input type for the generateSeoMetadata function.
 * @interface GenerateSeoMetadataOutput - Output type for the generateSeoMetadata function.
 * @function generateSeoMetadata - A function that calls the generateSeoMetadataFlow and returns the output.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const GenerateSeoMetadataInputSchema = z.object({
  examContent: z
    .string()
    .describe('The content of the exam, including questions and answers.'),
  focusKeywords: z
    .string()
    .describe(
      'Primary keywords related to the exam topic. Example: AI Exam Generator, Online Assessment'
    ),
});
export type GenerateSeoMetadataInput = z.infer<typeof GenerateSeoMetadataInputSchema>;

const GenerateSeoMetadataOutputSchema = z.object({
  title: z.string().describe('SEO-optimized title for the exam.'),
  description: z
    .string()
    .describe('SEO-optimized meta description for the exam.'),
  keywords: z.array(z.string()).describe('SEO-optimized keywords for the exam.'),
});
export type GenerateSeoMetadataOutput = z.infer<typeof GenerateSeoMetadataOutputSchema>;

export async function generateSeoMetadata(
  input: GenerateSeoMetadataInput
): Promise<GenerateSeoMetadataOutput> {
  return generateSeoMetadataFlow(input);
}

const generateSeoMetadataPrompt = ai.definePrompt({
  name: 'generateSeoMetadataPrompt',
  input: {schema: GenerateSeoMetadataInputSchema},
  output: {schema: GenerateSeoMetadataOutputSchema},
  prompt: `You are an SEO expert specializing in generating metadata for online exams.

  Given the content of the exam and the focus keywords, generate an SEO-optimized title, meta description, and a list of keywords.
  The title should be concise and engaging, the meta description should be compelling and include a call to action, and the keywords should be relevant to the exam content.

  Exam Content: {{{examContent}}}
  Focus Keywords: {{{focusKeywords}}}

  Ensure that the generated metadata is optimized for search engines to improve the exam's visibility.
  Structure the output according to the provided schema.
  `,
});

const generateSeoMetadataFlow = ai.defineFlow(
  {name: 'generateSeoMetadataFlow', inputSchema: GenerateSeoMetadataInputSchema, outputSchema: GenerateSeoMetadataOutputSchema},
  async input => {
    const {output} = await generateSeoMetadataPrompt(input);
    return output!;
  }
);
